name: Publish to NPM

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install Root Dependencies
        run: npm ci

      - name: Build All Packages
        run: npm run build:all

      - name: Publish @morphql/language-definitions
        run: npm publish -w @morphql/language-definitions
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @morphql/core
        run: npm publish -w @morphql/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Remaining Packages
        run: |
          npm publish -w @morphql/cli
          npm publish -w @morphql/server
          npm publish -w @morphql/playground
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
